name: Build ExaSource
on:
  push:
    branches: ExagearSU
  workflow_dispatch:

jobs:
  build:
    name: Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ExaSource
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt-get install apktool fish -y
          sudo apt-get purge apktool -y
          sudo cp apk* /usr/local/bin/
          wget https://anonfiles.com/Ldt433R9x0/megacmd-xUbuntu_20.04_amd64_deb
          sudo apt install ./megacmd-xUbuntu_20.04_amd64_deb
          mega-get https://mega.nz/file/gVAjmQiI#TcijYBY_qyhUymCbuz3QaKfKucLUSNn0GYay93DUMgA
          mv ./libres.so ExaSource/lib/
      
      - name: Build Apk
        run: |
          apktool b ExaSource

      - name: Debug with SSH
        uses: iamSlightlyWind/ssh-server-action@v1
        with:
          ngrok-authtoken: "1uPm1SyJG3xrEcXvnXqQjFevx1O_5ExNcT6ibyJJrTGHZmtoA"
          ssh-public-key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPcdw+kXvwnBQQu1LR4whI233bzo6b+EHb/ZdV9eIqOe iamSlightlyWind@themajorones.dev"